#!/bin/sh

unset USER GROUP ETCDIR WKRDIR REPODIR XBPSSRC ENDPOINT PUBPOINT LOGFILE ARGS

[ -f ./conf ] && . ./conf

: ${LOGFILE:=/dev/null}

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_import}
: ${GROUP:=_dxpb:_dxpb_import}

[ -z "$WRKDIR" -a -z "$REPODIR" ] && echo "Will not start - need a hostdir to own" && exit 1

args=""
[ -n "$REPODIR" ] && args="${args} -p $REPODIR"
[ -n "$REPOREMOTE" ] && args="${args} -P $REPOREMOTE"
[ -n "$XBPSSRC" ] && args="${args} -x $XBPSSRC"
[ -n "$ENDPOINT" ] && args="${args} -i $ENDPOINT"
[ -n "$PUBPOINT" ] && args="${args} -I $PUBPOINT"

[ -n "$WRKDIR" ] && cd "$WRKDIR"

exec chpst -u $USER:$GROUP dxpb-pkgimport-master $args $ARGS >$LOGFILE 2>&1
