#!/bin/sh

unset USER
unset GROUP
unset HOME

[ -f ./conf ] && . ./conf

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_import}
: ${GROUP:=_dxpb:_dxpb_import}

[ -z "$WRKDIR" -a -z "$REPODIR" ] && echo "Will not start - need a hostdir to own" && exit 1

args=""
[ -n "$REPODIR" ] && args="${args} -r '$REPODIR'"

[ -n "$WRKDIR" ] && cd "$WRKDIR"

exec chpst -u $USER:$GROUP dxpb-pkgimport-master $args
