#!/bin/sh

unset USER GROUP ETCDIR ARGS LOGFILE

[ -f ./conf ] && . ./conf

: ${LOGFILE:=/dev/null}

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_grapher}
: ${GROUP:=_dxpb:_dxpb_grapher:_dxpb_filer:_dxpb_ssl}

exec chpst -u $USER:$GROUP dxpb-grapher $ARGS >$LOGFILE 2>&1
