#!/bin/sh

unset USER GROUP ARGS ETCDIR LOGFILE

[ -f ./conf ] && . ./conf

: ${LOGFILE:=/dev/null}

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_frontend}
: ${GROUP:=_dxpb:_dxpb_frontend:_dxpb_graph:_dxpb_ssl}

exec chpst -u $USER:$GROUP dxpb-frontend $ARGS >$LOGFILE 2>&1
