#!/bin/sh

unset USER GROUP WRKDIR HOSTDIR SSLDIR ENDPOINT LOGFILE

[ -f ./conf ] && . ./conf

: ${LOGFILE:=/dev/null}

: ${USER:=_dxpb_files}
: ${GROUP:=_dxpb:_dxpb_files:_dxpb_ssl}

[ -z "$WRKDIR" -a -z "$HOSTDIR" ] && echo "Will not start - need a hostdir to own" && exit 1

args=""
[ -n "$SSLDIR" ] && args="$args -k $SSLDIR"
[ -n "$HOSTDIR" ] && args="$args -H $HOSTDIR"
[ -n "$ENDPOINT" ] && args="$args -f $ENDPOINT"

[ -n "$WRKDIR" ] && cd "$WRKDIR"

exec chpst -u $USER:$GROUP dxpb-hostdir-remote $args >$LOGFILE 2>&1
