#!/bin/sh

unset USER GROUP WRKDIR ETCDIR XBPSSRC ENDPOINT LOGFILE ARGS

getconf=
[ -f ./conf ] && . ./conf && getconf=no
[ -z "$getconf" -a -f ../dxpb-pkgimport-agent-generic/conf ] && . ../dxpb-pkgimport-agent-generic/conf

: ${LOGFILE:=/dev/null}

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_import}
: ${GROUP:=_dxpb:_dxpb_import}

[ -z "$WRKDIR" -a -z "$XBPSSRC" ] && echo "Will not start - need a path for xbps-src" && exit 1

args=""
[ -n "$XBPSSRC" ] && args="${args} -x $XBPSSRC"
[ -n "$ENDPOINT" ] && args="${args} -i $ENDPOINT"

[ -n "$WRKDIR" ] && cd "$WRKDIR"

exec chpst -u $USER:$GROUP dxpb-pkgimport-agent $args $ARGS >$LOGFILE 2>&1
