#!/bin/sh

unset USER
unset GROUP
unset HOME

[ -f ./conf ] && . ./conf

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_watcher}
: ${GROUP:=_dxpb}
: ${WRKDIR:=/etc/dxpb/}

cd "$WRKDIR"

exec chpst -u $USER:$GROUP dxpb-ircbot
