#!/bin/sh

unset USER GROUP HOME ETCDIR WRKDIR LOGFILE

[ -f ./conf ] && . ./conf

: ${LOGFILE:=/dev/null}

: ${ETCDIR:=/etc/dxpb/}
[ -f "${ETCDIR}/sv-common" ] && . "${ETCDIR}/sv-common"

: ${USER:=_dxpb_watcher}
: ${GROUP:=_dxpb}
: ${WRKDIR:=/etc/dxpb/}

cd "$WRKDIR"

exec chpst -u $USER:$GROUP dxpb-ircbot >$LOGFILE 2>&1
