/*
 * flyby.h
 */

#ifdef DXPB_DXPB_H
#error "Clean your dependencies"
#endif
#define DXPB_DXPB_H

#define DXPB_VERSION "0.0.1"
#define _POSIX_C_SOURCE 200809L

enum ret_codes {
	ERR_CODE_OK = 0,
	ERR_CODE_BAD,
	ERR_CODE_BADCALLER,
	ERR_CODE_BADDB,
	ERR_CODE_BADDEP,
	ERR_CODE_BADDIR,
	ERR_CODE_BADDOBBY,
	ERR_CODE_BADPKG,
	ERR_CODE_BADSOCK,
	ERR_CODE_BADWORLD,
	ERR_CODE_DONE,
	ERR_CODE_NO,
	ERR_CODE_NODB,
	ERR_CODE_NOFORK,
	ERR_CODE_NOMEM,
	ERR_CODE_NOPIPE,
	ERR_CODE_SADLIB,
	ERR_CODE_SADSOCK,
	ERR_CODE_YES,
	ERR_CODE_ZMQ,
};
enum fsm_state {
	FSM_STATE_A,
	FSM_STATE_B,
	FSM_STATE_C,
	FSM_STATE_D,
	FSM_STATE_E,
	FSM_STATE_F
};
