The following ABNF grammar defines the Package Import Managment Protocol:

    pkgimport_msg   = *( HELLO | ROGER | IFORGOTU | RUREADY | READY | RESET | INVALID | RDY2WRK | PING | PLZREADALL | IAMTHEGRAPHER | KTHNKSBYE | STABLESTATUSPLZ | STOP | TURNONTHENEWS | PLZREAD | DIDREAD | PKGINFO | PKGDEL | STABLE | UNSTABLE | WESEEHASH | HEREVIRTUALPKGS | VIRTPKGINFO )

    ;  No description

    HELLO           = signature %d1 proto_version
    signature       = %xAA %xA1             ; two octets
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    ROGER           = signature %d2 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    IFORGOTU        = signature %d3 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    RUREADY         = signature %d4 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    READY           = signature %d5 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    RESET           = signature %d6 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    INVALID         = signature %d7 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    RDY2WRK         = signature %d8 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    PING            = signature %d9 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    PLZREADALL      = signature %d10 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    IAMTHEGRAPHER   = signature %d11 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    KTHNKSBYE       = signature %d12 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    STABLESTATUSPLZ = signature %d13 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    STOP            = signature %d14 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  Used to trigger a git fast forward and reading of new packages.

    TURNONTHENEWS   = signature %d15 proto_version
    proto_version   = string                ; Package Import Management Protocol Version 00

    ;  No description

    PLZREAD         = signature %d16 proto_version pkgname
    proto_version   = string                ; Package Import Management Protocol Version 00
    pkgname         = string                ;

    ;  No description

    DIDREAD         = signature %d17 proto_version pkgname
    proto_version   = string                ; Package Import Management Protocol Version 00
    pkgname         = string                ;

    ;  No description

    PKGINFO         = signature %d18 proto_version info_revision pkgname version arch nativehostneeds nativetargetneeds crosshostneeds crosstargetneeds provides cancross broken bootstrap restricted
    proto_version   = string                ; Package Import Management Protocol Version 00
    info_revision   = string                ; Pkginfo Revision Within Protocol Version
    pkgname         = string                ;
    version         = string                ;
    arch            = string                ;
    nativehostneeds = longstr               ;
    nativetargetneeds = longstr             ;
    crosshostneeds  = longstr               ;
    crosstargetneeds = longstr              ;
    provides        = longstr               ;
    cancross        = number-1              ;
    broken          = number-1              ;
    bootstrap       = number-1              ;
    restricted      = number-1              ;

    ;  No description

    PKGDEL          = signature %d19 proto_version pkgname
    proto_version   = string                ; Package Import Management Protocol Version 00
    pkgname         = string                ;

    ;  No description

    STABLE          = signature %d20 proto_version commithash
    proto_version   = string                ; Package Import Management Protocol Version 00
    commithash      = string                ; Hash corresponding to git HEAD

    ;  No description

    UNSTABLE        = signature %d21 proto_version commithash
    proto_version   = string                ; Package Import Management Protocol Version 00
    commithash      = string                ; Empty field to mean "No"

    ;  No description

    WESEEHASH       = signature %d22 proto_version commithash
    proto_version   = string                ; Package Import Management Protocol Version 00
    commithash      = string                ; Hash of git HEAD as seen by persistent storage

    ;  No description

    HEREVIRTUALPKGS = signature %d23 proto_version virtualpkgs
    proto_version   = string                ; Package Import Management Protocol Version 00
    virtualpkgs     = longstr               ;

    ;  No description

    VIRTPKGINFO     = signature %d24 proto_version pkgname version arch depname deparch
    proto_version   = string                ; Package Import Management Protocol Version 00
    pkgname         = string                ;
    version         = string                ;
    arch            = string                ;
    depname         = string                ;
    deparch         = string                ;

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
